# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='programmer',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
