# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200604_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Programmer',
            new_name='ActivityRecord',
        ),
        migrations.RenameModel(
            old_name='Paradigm',
            new_name='UserModel',
        ),
        migrations.RemoveField(
            model_name='language',
            name='paradigm',
        ),
        migrations.RemoveField(
            model_name='activityrecord',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserModel'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='locations',
            field=models.ManyToManyField(to='user_app.Location'),
        ),
    ]
